In [116]:
print("The objective of this project it's to predict the higher value and the close value for each day")

The objective of this project it's to predict the higher value and the close value for each day

In [117]:
import pandas as pd

df = pd.read_csv("../../datasets/apple_stock.csv")
df

,Unnamed: 0,Adj Close,Close,High,Low,Open,Volume
0,1980-12-12,0.098834,0.128348,0.128906,0.128348,0.128348,469033600
1,1980-12-15,0.093678,0.121652,0.122210,0.121652,0.122210,175884800
2,1980-12-16,0.086802,0.112723,0.113281,0.112723,0.113281,105728000
3,1980-12-17,0.088951,0.115513,0.116071,0.115513,0.115513,86441600
4,1980-12-18,0.091530,0.118862,0.119420,0.118862,0.118862,73449600
...,...,...,...,...,...,...,...
11102,2024-12-27,255.589996,255.589996,258.700012,253.059998,257.829987,42355300
11103,2024-12-30,252.199997,252.199997,253.500000,250.750000,252.229996,35557500
11104,2024-12-31,250.419998,250.419998,253.279999,249.429993,252.440002,39480700
11105,2025-01-02,243.850006,243.850006,249.100006,241.820007,248.929993,55558000
11106,2025-01-03,243.860001,243.860001,244.179993,241.889999,243.369995,15135053

In [118]:
print("For market shares actions, we need to see the past for analyze the future, so we need to use the t-1 for t, so remove it the first target and last sample")

For market shares actions, we need to see the past for analyze the future, so we need to use the t-1 for t, so remove it the first target and last sample

## EDA FOR CLOSE VALUE

In [119]:
df.head()

   Unnamed: 0  Adj Close     Close      High       Low      Open     Volume
0  1980-12-12   0.098834  0.128348  0.128906  0.128348  0.128348  469033600
1  1980-12-15   0.093678  0.121652  0.122210  0.121652  0.122210  175884800
2  1980-12-16   0.086802  0.112723  0.113281  0.112723  0.113281  105728000
3  1980-12-17   0.088951  0.115513  0.116071  0.115513  0.115513   86441600
4  1980-12-18   0.091530  0.118862  0.119420  0.118862  0.118862   73449600

In [120]:
df['target_close'] = df['Close'].shift(-1)
df['target_high']  = df['High'].shift(-1)
df = df.dropna().reset_index(drop=True)
df['date'] = pd.to_datetime(df['Unnamed: 0'])

In [121]:
df

,Unnamed: 0,Adj Close,Close,High,Low,Open,Volume,target_close,target_high,date
0,1980-12-12,0.098834,0.128348,0.128906,0.128348,0.128348,469033600,0.121652,0.122210,1980-12-12
1,1980-12-15,0.093678,0.121652,0.122210,0.121652,0.122210,175884800,0.112723,0.113281,1980-12-15
2,1980-12-16,0.086802,0.112723,0.113281,0.112723,0.113281,105728000,0.115513,0.116071,1980-12-16
3,1980-12-17,0.088951,0.115513,0.116071,0.115513,0.115513,86441600,0.118862,0.119420,1980-12-17
4,1980-12-18,0.091530,0.118862,0.119420,0.118862,0.118862,73449600,0.126116,0.126674,1980-12-18
...,...,...,...,...,...,...,...,...,...,...
11101,2024-12-26,259.019989,259.019989,260.100006,257.630005,258.190002,27237100,255.589996,258.700012,2024-12-26
11102,2024-12-27,255.589996,255.589996,258.700012,253.059998,257.829987,42355300,252.199997,253.500000,2024-12-27
11103,2024-12-30,252.199997,252.199997,253.500000,250.750000,252.229996,35557500,250.419998,253.279999,2024-12-30
11104,2024-12-31,250.419998,250.419998,253.279999,249.429993,252.440002,39480700,243.850006,249.100006,2024-12-31
11105,2025-01-02,243.850006,243.850006,249.100006,241.820007,248.929993,55558000,243.860001,244.179993,2025-01-02

In [122]:
df['Close'] == df['Low']

0         True
1         True
2         True
3         True
4         True
         ...
11101    False
11102    False
11103    False
11104    False
11105    False
Length: 11106, dtype: bool

In [123]:
df['year'] = df['date'].dt.year
df['weekday'] = df['date'].dt.weekday
df['day'] = df['date'].dt.day
df['month'] = df['date'].dt.month
df

,Unnamed: 0,Adj Close,Close,High,Low,Open,Volume,target_close,target_high,date,year,weekday,day,month
0,1980-12-12,0.098834,0.128348,0.128906,0.128348,0.128348,469033600,0.121652,0.122210,1980-12-12,1980,4,12,12
1,1980-12-15,0.093678,0.121652,0.122210,0.121652,0.122210,175884800,0.112723,0.113281,1980-12-15,1980,0,15,12
2,1980-12-16,0.086802,0.112723,0.113281,0.112723,0.113281,105728000,0.115513,0.116071,1980-12-16,1980,1,16,12
3,1980-12-17,0.088951,0.115513,0.116071,0.115513,0.115513,86441600,0.118862,0.119420,1980-12-17,1980,2,17,12
4,1980-12-18,0.091530,0.118862,0.119420,0.118862,0.118862,73449600,0.126116,0.126674,1980-12-18,1980,3,18,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11101,2024-12-26,259.019989,259.019989,260.100006,257.630005,258.190002,27237100,255.589996,258.700012,2024-12-26,2024,3,26,12
11102,2024-12-27,255.589996,255.589996,258.700012,253.059998,257.829987,42355300,252.199997,253.500000,2024-12-27,2024,4,27,12
11103,2024-12-30,252.199997,252.199997,253.500000,250.750000,252.229996,35557500,250.419998,253.279999,2024-12-30,2024,0,30,12
11104,2024-12-31,250.419998,250.419998,253.279999,249.429993,252.440002,39480700,243.850006,249.100006,2024-12-31,2024,1,31,12
11105,2025-01-02,243.850006,243.850006,249.100006,241.820007,248.929993,55558000,243.860001,244.179993,2025-01-02,2025,3,2,1

In [124]:
df.drop(columns= ['Unnamed: 0', 'date'], inplace = True)
df

,Adj Close,Close,High,Low,Open,Volume,target_close,target_high,year,weekday,day,month
0,0.098834,0.128348,0.128906,0.128348,0.128348,469033600,0.121652,0.122210,1980,4,12,12
1,0.093678,0.121652,0.122210,0.121652,0.122210,175884800,0.112723,0.113281,1980,0,15,12
2,0.086802,0.112723,0.113281,0.112723,0.113281,105728000,0.115513,0.116071,1980,1,16,12
3,0.088951,0.115513,0.116071,0.115513,0.115513,86441600,0.118862,0.119420,1980,2,17,12
4,0.091530,0.118862,0.119420,0.118862,0.118862,73449600,0.126116,0.126674,1980,3,18,12
...,...,...,...,...,...,...,...,...,...,...,...,...
11101,259.019989,259.019989,260.100006,257.630005,258.190002,27237100,255.589996,258.700012,2024,3,26,12
11102,255.589996,255.589996,258.700012,253.059998,257.829987,42355300,252.199997,253.500000,2024,4,27,12
11103,252.199997,252.199997,253.500000,250.750000,252.229996,35557500,250.419998,253.279999,2024,0,30,12
11104,250.419998,250.419998,253.279999,249.429993,252.440002,39480700,243.850006,249.100006,2024,1,31,12
11105,243.850006,243.850006,249.100006,241.820007,248.929993,55558000,243.860001,244.179993,2025,3,2,1

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11106 entries, 0 to 11105
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Adj Close     11106 non-null  float64
 1   Close         11106 non-null  float64
 2   High          11106 non-null  float64
 3   Low           11106 non-null  float64
 4   Open          11106 non-null  float64
 5   Volume        11106 non-null  int64
 6   target_close  11106 non-null  float64
 7   target_high   11106 non-null  float64
 8   year          11106 non-null  int32
 9   weekday       11106 non-null  int32
 10  day           11106 non-null  int32
 11  month         11106 non-null  int32
dtypes: float64(7), int32(4), int64(1)
memory usage: 867.8 KB

In [127]:
df.describe()

,Adj Close,Close,High,Low,Open,Volume,target_close,target_high,year,weekday,day,month
count,11106.000000,11106.000000,11106.000000,11106.000000,11106.000000,1.110600e+04,11106.000000,11106.000000,11106.000000,11106.000000,11106.000000,11106.000000
mean,23.502389,24.337843,24.578397,24.072997,24.319354,3.154612e+08,24.359789,24.600372,2002.449757,2.018098,15.741311,6.544030
std,49.726178,50.176539,50.651338,49.641859,50.125999,3.348765e+08,50.219233,50.693652,12.718985,1.400500,8.747752,3.434378
min,0.037815,0.049107,0.049665,0.049107,0.049665,0.000000e+00,0.049107,0.049665,1980.000000,0.000000,1.000000,1.000000
25%,0.243323,0.300256,0.306362,0.292411,0.300045,1.111254e+08,0.300463,0.306379,1991.000000,1.000000,8.000000,4.000000
50%,0.446397,0.542411,0.553214,0.534040,0.542545,2.037224e+08,0.542411,0.553482,2002.000000,2.000000,16.000000,7.000000
75%,18.254964,21.376875,21.548303,21.104465,21.361696,3.960593e+08,21.401072,21.577678,2013.000000,3.000000,23.000000,10.000000
max,259.019989,259.019989,260.100006,257.630005,258.190002,7.421641e+09,259.019989,260.100006,2025.000000,4.000000,31.000000,12.000000