In [191]:
import pandas as pd

df = pd.read_csv('../../../datasets/e_sports.csv')

#  Geral Analyze of Data

In [192]:
# The shape of data
print(f'The shape of the data: {df.shape[0]} rows, {df.shape[1]} columns (features)')


# See the data, first view
df.head()

The shape of the data: 2800 rows, 16 columns (features)

,record_id,player_id,team_name,player_role,map_played,match_type,kills,assists,deaths,accuracy_percent,reaction_time_ms,fatigue_index,performance_score,win_probability,match_outcome,mvp_award
0,1,160,Titan Esports,Flex,Dust Arena,Playoff,18,6,7,40.43,192.28,0.52,50.02,0.83,Win,No
1,2,2,Titan Esports,Support,Neon City,Final,16,7,11,40.50,201.98,0.68,41.45,0.89,Win,No
2,3,468,Team Alpha,Support,Neon City,Semi-Final,14,7,15,36.93,172.50,0.27,35.77,0.81,Win,No
3,4,447,Team Nova,IGL,Desert Storm,Final,12,6,13,53.46,246.83,0.07,43.03,1.00,Win,No
4,5,196,Phantom Squad,Sniper,Skyline,Playoff,13,9,13,44.71,266.94,0.52,39.16,0.85,Win,No

In [193]:
df.describe()

,record_id,player_id,kills,assists,deaths,accuracy_percent,reaction_time_ms,fatigue_index,performance_score,win_probability
count,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000
mean,1400.500000,247.968214,14.872500,8.027857,10.025000,45.095225,220.129836,0.498875,45.306718,0.916364
std,808.434702,144.472383,3.973451,2.843157,3.178069,8.054907,30.240196,0.291618,10.333504,0.097468
min,1.000000,1.000000,4.000000,0.000000,1.000000,20.460000,118.730000,0.000000,16.580000,0.470000
25%,700.750000,121.000000,12.000000,6.000000,8.000000,39.542500,199.762500,0.240000,38.287500,0.860000
50%,1400.500000,248.000000,15.000000,8.000000,10.000000,44.960000,220.685000,0.500000,44.985000,0.950000
75%,2100.250000,371.000000,18.000000,10.000000,12.000000,50.552500,240.452500,0.760000,52.302500,1.000000
max,2800.000000,500.000000,30.000000,20.000000,22.000000,71.790000,324.110000,1.000000,87.360000,1.000000

#  DATA CLEANING and EDA

#### Data Cleaning

In [194]:
# Checking for features information:
for feature in df.columns:
    print(f'Feature: {feature}, differents values in the features: {df[feature].nunique()}')

# Checking for duplicated samples:
df_duplicated = df.duplicated().sum().sum()
print(f'\nTotal of duplicated samples: {df_duplicated}')
if df_duplicated and df_duplicated < (df.shape[0] / 10):
    df.drop_duplicates()

# Checking for null values in the features:
df_isnull = df.isnull().sum().sum()
print(f'Total of null values in the dataset: {df.isnull().sum().sum()}')
if df_isnull and df_isnull < (df.shape[0] / 10):
    df.dropna()

Feature: record_id, differents values in the features: 2800
Feature: player_id, differents values in the features: 497
Feature: team_name, differents values in the features: 6
Feature: player_role, differents values in the features: 5
Feature: map_played, differents values in the features: 5
Feature: match_type, differents values in the features: 5
Feature: kills, differents values in the features: 26
Feature: assists, differents values in the features: 20
Feature: deaths, differents values in the features: 22
Feature: accuracy_percent, differents values in the features: 1836
Feature: reaction_time_ms, differents values in the features: 2485
Feature: fatigue_index, differents values in the features: 101
Feature: performance_score, differents values in the features: 2009
Feature: win_probability, differents values in the features: 49
Feature: match_outcome, differents values in the features: 2
Feature: mvp_award, differents values in the features: 2

Total of duplicated samples: 0
Total of null values in the dataset: 0

#### Eda