# GET THE DATA

In [1]:
import pandas as pd


dataset = pd.read_csv("../../datasets/housing2_project4.csv")

# EDA + PREPROCESSING 1

In [5]:
# CONSTANT FEATYRES
dataset.nunique()

Square_Footage           894
Num_Bedrooms               5
Num_Bathrooms              3
Year_Built                73
Lot_Size                1000
Garage_Size                3
Neighborhood_Quality      10
House_Price             1000
dtype: int64

In [4]:
# REDUDANT FEATURES
dataset.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06

In [7]:
# DUPLICATED FEATURES
dataset.duplicated().sum()

np.int64(0)

In [8]:
# CARDINALITY FEATURES
dataset.nunique()

Square_Footage           894
Num_Bedrooms               5
Num_Bathrooms              3
Year_Built                73
Lot_Size                1000
Garage_Size                3
Neighborhood_Quality      10
House_Price             1000
dtype: int64

In [ ]:
# NEGATIVE SAMPLES
(dataset < 0).sum().sum()

np.int64(0)

In [ ]:
# NULL VALUES
dataset.isnull().sum()

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

In [14]:
# GET THE X AND Y
X = dataset.drop(columns= ['House_Price'])
y = dataset[["House_Price"]]

In [15]:
X.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
0,1360,2,1,1981,0.599637,0,5
1,4272,3,3,2016,4.753014,1,6
2,3592,1,2,2016,3.634823,0,9
3,966,1,2,1977,2.730667,1,8
4,4926,2,1,1993,4.699073,0,8

In [16]:
y.head()

    House_Price
0  2.623829e+05
1  9.852609e+05
2  7.779774e+05
3  2.296989e+05
4  1.041741e+06

# SPLIT AND PREPROCESSING 2

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# SPLIT THE DATA
X_train, x_test, Y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= 49)

# SCALING THE DATA
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
Y_train_scaled = scaler.fit_transform(Y_train)
x_test_scaled = scaler.fit_transform(x_test)
y_test_scaled = scaler.fit_transform(y_test)

# GET THE MODEL AND TRAIN

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score


# FIT THE MODEL
model = LinearRegression()
model.fit(X_train_scaled, Y_train_scaled)

# PREDICT AND ACCURACY OF THE TRAIN PART
y_preds_train = model.predict(X_train_scaled)
r2_train = r2_score(Y_train_scaled, y_preds_train)
print(f"The accuracy of train part r2 was: {r2_train*100:.2f}")


# PREDICT AND ACCURACY OF THE TEST PART
y_preds_test = model.predict(x_test_scaled)
r2_test = r2_score(y_test_scaled, y_preds_test)
print(f"The accuracy of test part r2 was: {r2_test*100:.2f}")

The accuracy of train part r2 was: 99.85
The accuracy of test part r2 was: 99.85