# GET THE DATA PART

In [6]:
import pandas as pd

df = pd.read_csv('../../datasets/e_sports.csv')
df.head()

,record_id,player_id,team_name,player_role,map_played,match_type,kills,assists,deaths,accuracy_percent,reaction_time_ms,fatigue_index,performance_score,win_probability,match_outcome,mvp_award
0,1,160,Titan Esports,Flex,Dust Arena,Playoff,18,6,7,40.43,192.28,0.52,50.02,0.83,Win,No
1,2,2,Titan Esports,Support,Neon City,Final,16,7,11,40.50,201.98,0.68,41.45,0.89,Win,No
2,3,468,Team Alpha,Support,Neon City,Semi-Final,14,7,15,36.93,172.50,0.27,35.77,0.81,Win,No
3,4,447,Team Nova,IGL,Desert Storm,Final,12,6,13,53.46,246.83,0.07,43.03,1.00,Win,No
4,5,196,Phantom Squad,Sniper,Skyline,Playoff,13,9,13,44.71,266.94,0.52,39.16,0.85,Win,No

# PREPROCESSING PART

In [7]:
from sklearn.preprocessing import OrdinalEncoder

deleted_features = ['record_id', 'player_id', 'team_name', 'player_role', 'map_played', 'match_type']
df.drop(columns=deleted_features, inplace = True)

encoder = OrdinalEncoder()
df['match_outcome'] = encoder.fit_transform(df[['match_outcome']])
df['mvp_award'] = encoder.fit_transform(df[['mvp_award']])

In [8]:
df

,kills,assists,deaths,accuracy_percent,reaction_time_ms,fatigue_index,performance_score,win_probability,match_outcome,mvp_award
0,18,6,7,40.43,192.28,0.52,50.02,0.83,1.0,0.0
1,16,7,11,40.50,201.98,0.68,41.45,0.89,1.0,0.0
2,14,7,15,36.93,172.50,0.27,35.77,0.81,1.0,0.0
3,12,6,13,53.46,246.83,0.07,43.03,1.00,1.0,0.0
4,13,9,13,44.71,266.94,0.52,39.16,0.85,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
2795,16,10,14,34.77,210.97,0.89,36.49,0.79,1.0,0.0
2796,17,9,7,43.17,201.52,0.50,52.59,0.86,1.0,0.0
2797,20,9,4,26.73,220.69,0.22,56.16,1.00,1.0,0.0
2798,14,9,10,56.56,174.82,0.35,51.78,1.00,1.0,0.0
2799,15,5,9,44.80,228.18,0.26,45.80,0.97,1.0,0.0

# SPLIT AND MODEL TRAIN PART

In [14]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['performance_score'])
y = df['performance_score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 41)

In [33]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import RandomizedSearchCV
import numpy as np


models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor()]

for model in models:
        print('--------------------------------------------')
        print(f"MODEL: {model}")


        # TRAIN THE MODEL
        model.fit(X_train, y_train)

        # SEE THE ACCURACY OF THE TRAIN
        y_preds_train = model.predict(X_train)
        r2 = r2_score(y_train, y_preds_train)
        mae = mean_absolute_error(y_train, y_preds_train)
        print(F"The accuracy in validation set it's: R2: {r2*100:.2f}%, mae:{mae:.3f}")


        # SEE THE ACCURACY OF THE TEST
        y_preds_test = model.predict(X_test)
        r2 = r2_score(y_test, y_preds_test)
        mae = mean_absolute_error(y_test, y_preds_test)
        print(F"The accuracy of in test set it's: R2: {r2*100:.2f}%, mae:{mae:.3f}")

--------------------------------------------
MODEL: LinearRegression()
The accuracy in validation set it's: R2: 100.00%, mae:0.003
The accuracy of in test set it's: R2: 100.00%, mae:0.003
--------------------------------------------
MODEL: DecisionTreeRegressor()
The accuracy in validation set it's: R2: 100.00%, mae:0.000
The accuracy of in test set it's: R2: 80.39%, mae:3.361
--------------------------------------------
MODEL: RandomForestRegressor()
The accuracy in validation set it's: R2: 99.20%, mae:0.690
The accuracy of in test set it's: R2: 93.86%, mae:1.877
--------------------------------------------
MODEL: KNeighborsRegressor()
The accuracy in validation set it's: R2: 86.08%, mae:3.065
The accuracy of in test set it's: R2: 79.65%, mae:3.818