# Understanding the model

In [199]:
import pandas as pd


df = pd.read_csv('../../../datasets/mushrooms.csv')
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [200]:
df.shape

(8124, 23)

### INFORMATIONS

https://www.kaggle.com/datasets/uciml/mushroom-classification

# EDA

- Check NULL and DUPLICATED
- Value of classes in the features

In [201]:
print(f"Null values: {df.isnull().sum().sum()}")
print(f"Duplicated values: {df.duplicated().sum().sum()}")

Null values: 0
Duplicated values: 0

In [202]:
df.nunique()

class                        2
cap-shape                    6
cap-surface                  4
cap-color                   10
bruises                      2
odor                         9
gill-attachment              2
gill-spacing                 2
gill-size                    2
gill-color                  12
stalk-shape                  2
stalk-root                   5
stalk-surface-above-ring     4
stalk-surface-below-ring     4
stalk-color-above-ring       9
stalk-color-below-ring       9
veil-type                    1
veil-color                   4
ring-number                  3
ring-type                    5
spore-print-color            9
population                   6
habitat                      7
dtype: int64

In [203]:
df.describe()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
count,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124,...,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124
unique,2,6,4,10,2,9,2,2,2,12,...,4,9,9,1,4,3,5,9,6,7
top,e,x,y,n,f,n,f,c,b,b,...,s,w,w,p,w,o,p,w,v,d
freq,4208,3656,3244,2284,4748,3528,7914,6812,5612,1728,...,4936,4464,4384,8124,7924,7488,3968,2388,4040,3148

# PREPROCESSING
- Features: OrdinalEncoder (0-x)
- Target 'class': Binary (LabelEncoder) (0/1)

In [204]:
X = df.drop(columns= ['class'], axis = 1)
y = df['class']

print(X.shape, y.shape)

(8124, 22) (8124,)

In [205]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

oe = OrdinalEncoder()
le = LabelEncoder()

X = oe.fit_transform(X)
y = le.fit_transform(y)

print(X.shape, y.shape)

(8124, 22) (8124,)

In [206]:
print(X)
print(y)

[[5. 2. 4. ... 2. 3. 5.]
 [5. 2. 9. ... 3. 2. 1.]
 [0. 2. 8. ... 3. 2. 3.]
 ...
 [2. 2. 4. ... 0. 1. 2.]
 [3. 3. 4. ... 7. 4. 2.]
 [5. 2. 4. ... 4. 1. 2.]]
[1 0 0 ... 0 1 0]

# SPLIT

In [207]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state= 42, shuffle= True)

print(f'Shape of train set: {X_train.shape}, {y_train.shape}')
print(f'Shape of test set: {X_test.shape}, {y_test.shape}')

Shape of train set: (6093, 22), (6093,)
Shape of test set: (2031, 22), (2031,)

# Selection of models 

 - Ensemble: Random Forests, XGBoost, LightGBM
 - Linear: Logistic
 - Instancies: KNNClassifier

In [208]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

models = [RandomForestClassifier(), XGBClassifier(), LGBMClassifier(),
          LogisticRegression(),
          KNeighborsClassifier()]

# Logic, train and metrics (Train 1)

In [212]:
import warnings
warnings.filterwarnings("ignore")

In [218]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

for model in models:
    print('------------------------------------------------------------------')
    print(f"Model: {model.__class__.__name__}")
    # TRAIN
    model.fit(X_train, y_train)

    # VERIFY OVERFITTING IN TRAIN SET
    y_preds_train = model.predict(X_train)
    accuracy = accuracy_score(y_train, y_preds_train)
    precision = precision_score(y_train, y_preds_train)
    recall = recall_score(y_train, y_preds_train)
    f1 = f1_score(y_train, y_preds_train)
    cm = confusion_matrix(y_train, y_preds_train)

    print(f"Metrics of train: Accuracy: {accuracy} | Precision: {precision} | Recall: {recall} | F1: {f1} | Confusion Matrix: {cm}")


    # TEST SET (METRICS)
    y_preds_test = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_preds_test)
    precision = precision_score(y_test, y_preds_test)
    recall = recall_score(y_test, y_preds_test)
    f1 = f1_score(y_test, y_preds_test)
    cm = confusion_matrix(y_test, y_preds_test)

    print(f"Metrics of train: Accuracy: {accuracy} | Precision: {precision} | Recall: {recall} | F1: {f1} | Confusion Matrix: {cm}")

------------------------------------------------------------------
Model: RandomForestClassifier
Metrics of train: Accuracy: 1.0 | Precision: 1.0 | Recall: 1.0 | F1: 1.0 | Confusion Matrix: [[3168    0]
 [   0 2925]]
Metrics of train: Accuracy: 1.0 | Precision: 1.0 | Recall: 1.0 | F1: 1.0 | Confusion Matrix: [[1040    0]
 [   0  991]]
------------------------------------------------------------------
Model: XGBClassifier
Metrics of train: Accuracy: 1.0 | Precision: 1.0 | Recall: 1.0 | F1: 1.0 | Confusion Matrix: [[3168    0]
 [   0 2925]]
Metrics of train: Accuracy: 1.0 | Precision: 1.0 | Recall: 1.0 | F1: 1.0 | Confusion Matrix: [[1040    0]
 [   0  991]]
------------------------------------------------------------------
Model: LGBMClassifier
Metrics of train: Accuracy: 1.0 | Precision: 1.0 | Recall: 1.0 | F1: 1.0 | Confusion Matrix: [[3168    0]
 [   0 2925]]
Metrics of train: Accuracy: 1.0 | Precision: 1.0 | Recall: 1.0 | F1: 1.0 | Confusion Matrix: [[1040    0]
 [   0  991]]
------------------------------------------------------------------
Model: LogisticRegression
Metrics of train: Accuracy: 0.9501066797964878 | Precision: 0.9570980118590862 | Recall: 0.9381196581196581 | F1: 0.9475138121546961 | Confusion Matrix: [[3045  123]
 [ 181 2744]]
Metrics of train: Accuracy: 0.9497784342688331 | Precision: 0.9485368314833501 | Recall: 0.9485368314833501 | F1: 0.9485368314833501 | Confusion Matrix: [[989  51]
 [ 51 940]]
------------------------------------------------------------------
Model: KNeighborsClassifier
Metrics of train: Accuracy: 0.9998358772361726 | Precision: 0.9996582365003418 | Recall: 1.0 | F1: 0.9998290890446078 | Confusion Matrix: [[3167    1]
 [   0 2925]]
Metrics of train: Accuracy: 0.9960610536681438 | Precision: 0.9929789368104313 | Recall: 0.9989909182643795 | F1: 0.9959758551307847 | Confusion Matrix: [[1033    7]
 [   1  990]]

### Here the better model are that correctly identifies the positive ones, that is, if it predicted any that were poisonous or not poisonous, then we have to look into that, and that's called a false negative, so we need to look ate RECALL ACCURACY.